### ISSUE TITLE
Django 5.0 warnings: baseconv is deprecated

### ISSUE THREAD

**Issue by MrSage** [georgemarshall/django-cryptography#74]
```
RemovedInDjango50Warning: The django.utils.baseconv module is deprecated.
    from django.utils import baseconv
```
https://code.djangoproject.com/ticket/32712

```
# django_cryptography/core/signing.py
- from django.utils import baseconv
+ from django.core.signing import b62_encode, b62_decode
```

**Comment by MrSage** [comment]
I can't create a PR for this repo but here is the diff:


```diff
diff --git a/django_cryptography/core/signing.py b/django_cryptography/core/signing.py
index 73ccc7f..c64f526 100644
--- a/django_cryptography/core/signing.py
+++ b/django_cryptography/core/signing.py
@@ -17,7 +17,7 @@ from django.core.signing import (
     b64_encode,
     get_cookie_signer,
 )
-from django.utils import baseconv
+from django.core.signing import b62_encode, b62_decode
 from django.utils.encoding import force_bytes, force_str
 
 from ..utils.crypto import constant_time_compare, salted_hmac
@@ -138,7 +138,7 @@ class Signer:
 
 class TimestampSigner(Signer):
     def timestamp(self):
-        return baseconv.base62.encode(int(time.time()))
+        return b62_encode(int(time.time()))
 
     def sign(self, value):
         value = force_str(value)
@@ -152,7 +152,7 @@ class TimestampSigner(Signer):
         """
         result = super().unsign(value)
         value, timestamp = result.rsplit(self.sep, 1)
-        timestamp = baseconv.base62.decode(timestamp)
+        timestamp = b62_decode(timestamp)
         if max_age is not None:
             if isinstance(max_age, datetime.timedelta):
                 max_age = max_age.total_seconds()
```

**Comment by georgemarshall** [comment]
I am going to sit on this for now, as I have been re-working the code to add type information. Django 5.0 isn't set to be release until December 2023o over a full year from now.

The unfortunate part is Django 3.2 will still be supported until April 2024. So a compatibility shims will be needed, or Django 3.2 support will be dropped once Django 5.0 is released.

**Comment by rburhum** [comment]
Getting close to that December date :-)

**Comment by MrSage** [comment]
@georgemarshall , would this not be as easy as:

```python
try:
    from django.core.signing import b62_encode as encode
    from django.core.signing import b62_decode as decode
except ImportError:
    from django.utils import baseconv
    encode = baseconv.base62.encode
    decode = baseconv.base62.decode

...

 class TimestampSigner(Signer):
     def timestamp(self):
-        return baseconv.base62.encode(int(time.time()))
+        return encode(int(time.time()))
 
     def sign(self, value):
         value = force_str(value)
@@ -152,7 +152,7 @@ class TimestampSigner(Signer):
         """
         result = super().unsign(value)
         value, timestamp = result.rsplit(self.sep, 1)
-        timestamp = baseconv.base62.decode(timestamp)
+        timestamp = decode(timestamp)
         if max_age is not None:
             if isinstance(max_age, datetime.timedelta):
                 max_age = max_age.total_seconds()
```

Using `try:except:` to handle compatibility through imports is pretty powerful, and its easy to cleanup when the compatibility is no longer needed.

**Comment by jameslao** [comment]
Django 5.0 release is around the corner... any plan to fix this?

**Comment by saurav-codes** [comment]
Django 5 is released and i am having this error -
```bash
  File "/Users/sauravsharma/Developer/work/TPA/worktree_archipay/django-5-upgrades/env/lib/python3.10/site-packages/django_cryptography/core/signing.py", line 20, in <module>
    from django.utils import baseconv
ImportError: cannot import name 'baseconv' from 'django.utils' 
```

**Comment by saurav-codes** [comment]
alright, i fixed the issue.

- first i cloned the repo in my django project.
- `cd django-cryptography`
- `pip install -e .`

initially i tried with `pip install --upgrade django-cryptography` but that didn't update the package so then i tried to install it with git repo but then it doesn't install it correctly. the `core` folder was missing. finally at the last above method works.

It seems the issue may be related to the package configuration for installation directly from the repository. The `setup.py` or `pyproject.toml` may not be including necessary sub-packages or dependencies for a correct install.

**Comment by saurav-codes** [comment]
i found the issue in `setup.cfg`.  after this change, i can directly install from the repo and the subfolders ( the `core` folder ) is also included now. idk may be this may not be issue as i am unaware of the third party package code structure but since this change solves the issue, i created a PR here #106

**Comment by alexander-schillemans** [comment]
The 1.1 release on PyPi does not include the updated import statements in the core/signing.py which is throwing errors.
@georgemarshall Any chance you can push the new version to PyPi?

**Comment by jmaddington** [comment]
> As of now for those who are having issues can do -
> 
> > pip install "git+https://github.com/saurav-codes/django-cryptography"

This is for Django 5.0? As opposed to the comment that MrSage made [above](https://github.com/georgemarshall/django-cryptography/issues/74#issuecomment-1766461463)?

**Comment by MrSage** [comment]
Just as a general note, using an unmaintained cryptography library is probably not a good idea. I found some of the patterns shared here were quite extensible and dodged the problem:

https://www.piiano.com/blog/field-level-encryption-in-python-for-django-applications

**Comment by jmaddington** [comment]
As in you used approach 1 or 2 there?

**Comment by iyedeisaiah** [comment]
I reverted to django 4.1.3 and this solved the issue. Warning though other dependecies that depend on django 5.0 like crispy forms, django_q would have to be updated accordingly

**Comment by vitaliyf** [comment]
This change was already merged to master of this repository as part of https://github.com/georgemarshall/django-cryptography/pull/97 - just hasn't been released to PyPi yet.

**Comment by Redowan-Ahmed** [comment]
I'm using Django 5.0, To use the Django_cyptography,
Currently, I'm using this command because the Pypy is not updated yet 
`pip install "git+https://github.com/saurav-codes/django-cryptography"`

**Comment by vhalis** [comment]
The change in #106 is required for installing from pip. Thanks @saurav-codes for the alternative for now and for the PR!

For those looking for the fix but want to be safe if you need to use a requirements file, you can pin to the commit hash:

`django-cryptography @ git+https://github.com/saurav-codes/django-cryptography.git@ac210338dd2c84a410452e0b8e18ddee43f1920f`

For pip above version 20.1

**Comment by adrenaline681** [comment]
Any update? Its already been over 3 months since Django 5 got released and we still can't install django-cryptography properly

**Comment by kirienko** [comment]
It seems that this issue is solved in #97 and therefore can be closed.

**Comment by chrisclark** [comment]
The issue is that there is no release that has been made -- not that it is not resolved in the code.

**Comment by adrenaline681** [comment]
> The issue is that there is no release that has been made -- not that it is not resolved in the code.

Yes, please can we get a new release with these changes?

**Comment by chrisclark** [comment]
Concretely -- if a package depends on django-cryptography and that package wants to release to pypi, it can't happen without a release of this change first. A pinned github hash in the requirements will be rejected from pypi.

**Comment by chrisclark** [comment]
I have forked the project, updated some dependencies, and published on pypi here:
https://pypi.org/project/django-cryptography-django5/

You can see the fork (and the code) here:
https://github.com/chrisclark/django-cryptography/

Feel free to pip install that version for anyone who needs it. Hopefully the changes can be brought into the official project soon. I hate to maintain a weird fork like this.

Simply: `pip install django-cryptography-django5==2.2`

**Comment by redblacktree** [comment]
Can we please get a comment from the authors on the pypi release? What is preventing this from happening? Do you need help resolving some issues?

**Comment by MrCocoDev** [comment]
Open source projects are created and abandoned all the time. Forking the repo and petitioning Pypi for the original name doesn’t seem so farfetched to me.

**Comment by chrisclark** [comment]
> Open source projects are created and abandoned all the time. Forking the repo and petitioning Pypi for the original name doesn’t seem so farfetched to me.

I agree in theory, but in practice I don’t intend on maintaining this indefinitely; if someone wants to pick up the mantle that would be great but it ain’t me, hah! This was easy since I was just updating some dependencies and incorporating changes others had already proposed. But I don’t know the codebase and *certainly* don’t have the expertise to be touching a bunch of crypto stuff. I promise no one wants me doing that :)

**Comment by ailandini-accenture** [comment]
Did anyone here switch to a different cryptology package? I'm having a lot of trouble finding one that is explicitly Django 5.0 compatible and actively maintained.

**Comment by pataquets** [comment]
On a cursory status check, maintainer seems quite unresponsive lately (which is understandable, since he has no obligation, keep in mind) and I'm wondering if he might be swamped by work, lost interest, not getting notifications or anything else. Sometimes it's just a newborn baby, which understandably pushes projects aside :smile:.
I wonder if he might use some help (e.g. appointing co-mainteiners) or want to hand off project maintenance if he's lost interest/not using it anymore, which is perfectly fine.
So, I'm pinging @georgemarshall directly to increasing odds the notification finds its way and letting him know there is people interested who might want to step in to keep the project alive (thumb-up this comment to voice your interest). Just a quick note about reasonable expectations will be enough to make everyone aware and proceed forward.
I'll leave this comment for a while before opening a typical "Project maintenance status" issue (which it might be necessary anyway). I've had some success reviving/keeping projects alive this way in the past, and no doubt this one deserves better than just fade away silently, given the user base (read: potential candidate [co-]maintainers).

@georgemarshall Also, creating a Github organization and transferring the project might be an easy/useful first step for later adding [co-]maintainers you deem trustworthy.
In any case, thanks for considering and also thanks for sharing your work. Hope you're doing well.

**Comment by iklobato** [comment]
Django5 need some general fixes at django_q/core_signing.py, downgrade to latest LTS version:
```
pip install -U Django==4.2
```

**Comment by akhileshThapliyal** [comment]
Any idea when the package for Djnago 5.x will be released?

**Comment by rburhum** [comment]
@akhileshThapliyal  use @chrisclark version for now. His fork includes the support for Django 5.x that you need.

**Comment by Armagad1972** [comment]
Hello,
It seems that it still not working:
![image](https://github.com/user-attachments/assets/d34ca774-7465-402e-982f-a7a19057c078)
Any chance to correct it ?

**Comment by ailandini-accenture** [comment]
@Armagad1972 I wouldn't hold your breath. 
You didn't ask for it, but if you want my advice, I'd suggest forking the repo and fixing it like others have done above.
It seems crypto libraries in general aren't overtly maintained, so until someone steps up, you'll likely want to handle it yourself if you want something stable.

**Comment by Armagad1972** [comment]
@ailandini-accenture Thanks for your answer, but I have done by git and it works perfectly.
I will check if I will really need further

**Comment by noesis-software-technologies** [comment]
as a work around I went into my directory where the import is made -> deleted the import and paste for the moment 

        class BaseConverter(object):
            decimal_digits = "0123456789"
            
            def __init__(self, digits):
                self.digits = digits
            
            def from_int(self, i):
                return self.convert(i, self.decimal_digits, self.digits)
            
            def to_int(self, s):
                return int(self.convert(s, self.digits, self.decimal_digits))
            
            def convert(number, fromdigits, todigits):
                # Based on http://code.activestate.com/recipes/111286/
                if str(number)[0] == '-':
                    number = str(number)[1:]
                    neg = 1
                else:
                    neg = 0
        
                # make an integer out of the number
                x = 0
                for digit in str(number):
                   x = x * len(fromdigits) + fromdigits.index(digit)
            
                # create the result in base 'len(todigits)'
                if x == 0:
                    res = todigits[0]
                else:
                    res = ""
                    while x > 0:
                        digit = x % len(todigits)
                        res = todigits[digit] + res
                        x = int(x / len(todigits))
                    if neg:
                        res = '-' + res
                return res
            convert = staticmethod(convert)
        
        base2 = BaseConverter('01')
        base16 = BaseConverter('0123456789ABCDEF')
        base36 = BaseConverter('0123456789abcdefghijklmnopqrstuvwxyz')
        base62 = BaseConverter(
            '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
        )

**Comment by czue** [comment]
I got frustrated with all the other workarounds, so decided to [publish a new package on pypi](https://pypi.org/project/django-cryptography-5/). You can now run:

```
pip install django-cryptography-5
```

to get the version of this library that is compatible with Django 5.0.

Note: I am not familiar with the code of this library at all and am not taking on a "maintainer" role or able to fix bugs. I just wanted something that I could pip install into my projects and thought it might benefit others too. Use it at your own risk.

**Comment by czue** [comment]
ugh, I just realized someone already did this and I just didn't see [the comment](https://github.com/georgemarshall/django-cryptography/issues/74#issuecomment-2147974857) because it was collapsed on Github. 🤦 

```
pip install django-cryptography-django5
```

Should also hopefully work.

**Comment by chrisclark** [comment]
@czue funny that we made almost the same comment about not wanting to become a maintainer though. Hah!

**Comment by CrazyChief** [comment]
Hey)
Any updates expected on this in the near future?

**Comment by ghost** [comment]
> I have forked the project, updated some dependencies, and published on pypi here: https://pypi.org/project/django-cryptography-django5/
> 
> You can see the fork (and the code) here: https://github.com/chrisclark/django-cryptography/
> 
> Feel free to pip install that version for anyone who needs it. Hopefully the changes can be brought into the official project soon. I hate to maintain a weird fork like this.
> 
> Simply: `pip install django-cryptography-django5==2.2`

Hi @chrisclark ,

Any support for python3.13?

**Comment by osahene** [comment]
> As of now for those who are having issues can do -
> 
> > pip install "git+https://github.com/saurav-codes/django-cryptography"

This worked.

**Comment by King-Austin** [comment]
Can't thank you guys enough for the package fix, github repo and the workaround. thanks alot

am really exhausted using a custom python function, which is still not compatible with my django admin in terms of rendering and CRUD operation.

**Comment by jonesnc** [comment]
Looks like `django-cryptography-5` is the more consistently maintained version.
